name: Dev Build on Push

on:
  push: 
    branches: dev
  workflow_dispatch:
    
jobs:
  build:  
    runs-on: windows-latest
  
    steps:
      - name: Build Project
        run: dotnet build RootTest/RootTest.csproj
      
      
      - name: Setup NuGet
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest
          
      
          
    
